travis:
  secure:
    BINSTAR_TOKEN: dax2UA+wJG4pdxupKSl/mOL/TN5jGOf2kjiSy8Gm4A/FLAJtGm3yrSUQwQRflRo4dx/PdMtEBmGtM1CnkAA5zuGesoFi1ilXx9zxVCi1koTD0x8O/ks4uAP8rlCcRUAPRCtxJOSWtaqKc7SdCu0g9ZDWeXN0FgX/OtL6V0Vj+wjVb/PrO/hicUdv1Vw/osNvbqSnOIjLQmK8GqX/kM8z719Hhkmj3jm40wsLyaN6IWL0xcwh0U4U651eXIujXC02NZpvykHyB0u1YG0S4sNgLPb5QL0gLQMwKzJmZ20eBU0M2tGio1vw9Hk3m6mupkIAvzLjlv4eTiIfj42QTgzjkax93sNCgEmC8cPr8YpYkCTb+OMQkpQb3fC50529RlfvoCRJOYxKPa9kQUBVW2L8o7E1XCDeIe/pubZeynhtVcX3uMyC4c7Y4fT6vpyM/o8qJj+Gl46ukETME/oP52r602GdqfSrPlkzvLSOFWDQuc5+oql6puvrN10VlKcDomLyvB/E9jdNF5cJAC8Pfy58/lmuKZ82hEu9qgTseimKUB1QSdN87wgKu2k/FfedS4zWljc3HAtVgLQLLoetBUcDkz+/9Du3qECYoDKYfWgN+zlz9tjQNGn9zqbgTNEVeum4J0Z9oCJ9JQoMFIWYVFlKY/b9U3TDqMdEb21nkJDtlpw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
