appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: U33GtXoXIi+yl5ZMdsLDwVUQA3Z1OMQcA0Tbyd2cQ/lTib3af64m6knYMZzv1W394fHun8IKPtbsxUYjWK8U8ywzO9FTW1+9lV6WJJtCNWIAeeb27PeZdQwCyeQDf3qMl60BrtUInq+GVcMj2eY0iyd8ZzOUarxt4zB+wWH0aRa0lSdbK5GOJ2K1o3Tw2al1xNKs3Fw8SaO6GC2+gxOwb8ZITqLJVWkE3V9uqoncic2gUWb+o1DDTIbDeO634e7iGQ/fIl8jZQDUkhSs2IqZ8j8G8CmkpJ6hGzEM6HEmssO/EIxqIDTPzyaer2Jifa3c9LVyqovdIWAQQiaYYB+uwje89+rnv5RVCGfpLPVoOEx8sVfWuaLrDqTEMaUAqXFGwI9XJjJguG0wYOmvtl6HAOu5PVPb4mwr/8+o1RBX0YrO+HZxeNN/9+sS4kQ9LhVhaDopjlsZFTY4sp4RXW0b0jhGhsrfGEMCNbb+uod5H0Mee7c5lCW0ahmAbOn61EzkmixKretcMjdR+a8sxM2cNHezeQAJ7i7I9cT5AAGX6ei+82KzIPse/CGr3wMHcJJbqMFyqGu2BfHk0aeRYhQnkxoVaZ2WHDpQfhIVjqEZYVBgzLcQQm8RM0Hvw+rqJFPR8mM7kxpVDHdilVXSiZ0q5cS167eUWKmPFJnqtjPpdZI=}
conda_forge_output_validation: true
